name: CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sanity check paths
        run: |
          python - << 'PY'
          import os
          print("CWD:", os.getcwd())
          print("Top level:", os.listdir("."))
          print("MLProject:", os.listdir("MLProject"))
          print("Dataset:", os.listdir("MLProject/namadataset_preprocessing"))
          PY

      - name: Run training script
        run: |
          python MLProject/modelling.py

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: validation-artifacts
          path: validation_report.txt
          if-no-files-found: error
